### ISSUE TITLE
Need to update to newest fastp

### ISSUE THREAD

**Issue by benkraj** [nf-wrap/main#23]
### Description of the bug

It looks like your fastp is a few commits behind the nf-core module, and it has an annoying bug around --std-out being included in single-end mode.

https://github.com/nf-core/modules/commit/20a508676f40d0fd3f911ac595af91ec845704c4

This can then bloat log files (and on AWS lead to considerable charges).

![image](https://github.com/nf-wrap/main/assets/23386334/88c6eb7e-5337-4ef1-b372-7d2508163591)

There are a few other commits that might be worth including with an update.

**Comment by maxulysse** [comment]
Good point, I'm on it, thanks

**Comment by benkraj** [comment]
Thanks very much, @maxulysse !

**Comment by maxulysse** [comment]
this has been fixed in `dev`, I need to add some more tests for the other tools, and then I'll work on a release
